### ISSUE TITLE
Issues with opentelemetry 1.4.0

### ISSUE THREAD

**Issue by enablingTeamMobile** [signalfx/splunk-otel-ios#128]
Yesterday opentelemetry released version 1.4.0 as a pre-release. By default splunk otel uses this version as a dependency which did break our builds. We had to manually revert the version back to 1.3.1 to fix this. 
Can someone have a look at this and, if necessary, implement the changes needed in the splunk swift package to make it fully compatible to opentelemetry 1.4.0 or manually fix the version in the swift package to 1.3.1?

Thanks

**Comment by johnbley** [comment]
Thanks for alerting us to this!
