### ISSUE TITLE
Redefinition error of sqlite with existing libraries in iOS

### ISSUE THREAD

**Issue by celinahiyasjavier** [signalfx/splunk-otel-ios#139]
Hi, 

Encountering this issue with existing WCDB library when integrating splunk in iOS. Is it possible for splunk to only contain sqlite within the package to avoid redefinition error when integrating it to apps with third party libraries already using sqlite?

**Comment by jnino-splunk** [comment]
Hello @celinahiyasjavier,

I was wondering if you had a little bit more details on your exact issue and how you are setup? I am guessing that WCDB is being added through CocoaPods? Some users have solved this issue in the past by removing the `use_frameworks!` line (if present and adding `use_modular_headers!` instead.

**Comment by celinahiyasjavier** [comment]
@jnino-splunk Thank you for this. Current workaround we made was renaming conflicting symbols in WCDB.
