### ISSUE TITLE
Cannot disable slow rendering detection

### ISSUE THREAD

**Issue by maciejczechowski** [signalfx/splunk-otel-ios#148]
Hello!
[According to the docs](https://docs.splunk.com/Observability/gdi/get-data-in/rum/ios/configure-rum-ios-instrumentation.html) we should have `slowRenderingDetectionEnabled` option that control whether slow rendering detection is enabled.

Looking at the code, such option does not exist and `startSlowFrameDetector` is called unconditionally in `SplunkRum.initliaze`. 
Could it be added so that code reflects the docs? We're still evaluating usefulness of this instrumentation, and like to have option to opt-out.

**Comment by johnbley** [comment]
Release `0.11.1` added `slowRenderingDetectionEnabled`, hopefully more properly this time 😄
