### ISSUE TITLE
Allow setting scheduleDelay for BatchSpanProcessor

### ISSUE THREAD

**Issue by maciejczechowski** [signalfx/splunk-otel-ios#149]
`BatchSpanProcessor` seems to have option to configure exporting frequency, defaulting to 5s.
`SplunkRum.initialize` always uses the defaults, hence it's impossible to change that parameter - and 5s might be too often for us. 

It seems that adding a simple configuration param should solve this issue.

**Comment by johnbley** [comment]
Release `0.11.1` adds `bspScheduleDelay` to address this.
