### ISSUE TITLE
Parsing server-timing header doesn't account for multiple values

### ISSUE THREAD

**Issue by seemk** [signalfx/splunk-otel-ios#161]
For example the `server-timing` header with a value of `foo; bar=42, traceparent;desc="00-b4cfffe039d464890cf09c1dd766a130-9994088852321abc-01"` will fail to be parsed correctly as the value does not start with `traceparent`: https://github.com/signalfx/splunk-otel-ios/blob/main/SplunkRumWorkspace/SplunkRum/SplunkRum/NetworkInstrumentation.swift#L45

**Comment by jek-bao-choo** [comment]
Hi @seemk Greetings! Thank you for looking into this.

**Comment by seemk** [comment]
Fix incoming here: https://github.com/signalfx/splunk-otel-ios/pull/162
