### ISSUE TITLE
Cocoapod support?

### ISSUE THREAD

**Issue by sanu** [signalfx/splunk-otel-ios#41]
Hello,

Isn't this available on Cocoapods?

Thanks,
Sanu

**Comment by johnbley** [comment]
Hi Sanu - it is not.  The best way to use with cocoapods is to use Swift Package Manager to import `splunk-otel-ios` in your main project (not the `Pods` project in the workspace - this will get regenerated when you run `pod install` and lose the swift package).  I will work on updating the docs for this, thanks!

**Comment by AmerigoM** [comment]
@sanu now it's possible to use Cocoapods to install the library as per the [documentation](https://docs.splunk.com/observability/gdi/get-data-in/rum/ios/install-rum-ios.html).
Add `pod 'SplunkOte'` to your podfile and then execute:
```
pod install --repo-update
```
