### ISSUE TITLE
Issue with extensions

### ISSUE THREAD

**Issue by 3latko** [signalfx/splunk-otel-ios#62]
When I use the library in the main target, everything is fine. But when I import it in an extension, for example in Notification Service Extension, during compile time I get this error:
`Missing required module '_AtomicsShims'`

Do you know what could be the issue?

**Comment by seemk** [comment]
Hi, do you have `SplunkOtel` in your `Frameworks and Libraries` list?

**Comment by 3latko** [comment]
Hi, ah yes, now I realise it's a brain fart on my side... 
Not sure I didn't check this there first. Thanks for the answer though, I will close this.
